== What is Monitor?

_Monitor_ is general purpose monitoring agent, with easily added individual monitors for things like logs, server parameters, websites, etc.  Each monitor is run periodically (configured separately for each monitor).  Monitor accepts no inputs, and outputs MOP events or status messages.

=== The individual monitors

==== NTPServer

This monitors my TF-1006-PRO NTP server.

.MOP events produced
|===
|Tag|Description
|NTPServer.readFailure
|Sent at most once per hour when the monitor is unable to read status information from the TF-1006-PRO NTP server.
|===


== Dependencies

_EmailService_ has several dependencies:

* _Util_ is an utilities module the author also wrote, freely available from https://github.com/SlightlyLoony/Util[here].
* _MOP_ is the bog-standard Java JSON module, freely available from https://github.com/stleary/JSON-java[here].

== Why is Monitor's code so awful?

The author is a retired software and hardware engineer who did this just for fun, and who (so far, anyway) has no code reviewers to upbraid him. Please feel free to fill in this gap! You may contact the author at link:mailto:[tom@dilatush.com].

== How is Monitor licensed?

EmailService is licensed with the quite permissive MIT license:

....
Created: April 18, 2023
Author: Tom Dilatush link:mailto:tom@dilatush.com
Github: https://github.com/SlightlyLoony/Monitor
License: MIT

Copyright 2023 by Tom Dilatush (aka "SlightlyLoony")

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE A AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
....